spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dormitory?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: abc123
  jackson:
    date-format: yyyy年MM月dd日

server:
  port: 8080
  servlet:
    context-path: /dormitory

mybatis:
  mapper-locations: com/AWR/mapper/*.xml

logging:
  level:
    com:
      AWR:
        mapper: debug

pagehelper:
  helper-dialect: mysql       # 根据方言来选择合适的分页方式
